webhook_logger.webhook_logger.*:
  type: config_entity
  label: 'Webhook Logger config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
